### PR TITLE
simulations tags and list of releases in README

### PR DESCRIPTION
**Pull request by zonca**

### CODE REVIEW

**Comment by zonca** [comment]
@aiolasimone I am merging this so that the new tag names are available during the AWG Zoom day,
please send feedback here anyway and I'll implement fixes in separate commits

**Comment by aiolasimone** [comment]
This looks good @zonca. The same naming was used by @TaiSakuma in the SO Product DB for your map sims (https://simons1.princeton.edu/products/ui/simulations).

**Comment by zonca** [comment]
ok, where do I find the username and password to access the product db?

**Comment by zonca** [comment]
ok, got it, thanks

**Pull request merged**
