### PR TITLE
Run 2 simulations: highres foreground in equatorial, variable spectral index

### PR DESCRIPTION
**Pull request by zonca**
Rerun of `201903_highres_foregrounds` in Equatorial

### CODE REVIEW

**Comment by zonca** [comment]
@NicolettaK @msyriac please review the `README.md`, maps are temporarily in `/global/cscratch1/sd/zonca/simonsobs/mapsims_runs/201904_highres_foregrounds_equatorial`, 512 are available, 4096 in the queue.

Plots at https://gist.github.com/zonca/0e6d1a16f4afdb1dcc7859f3262fdd9f

**Comment by zonca** [comment]
In this pull request I am preparing 3 simulations, check the readmes: https://github.com/simonsobs/map_based_simulations/pull/6/files?file-filters%5B%5D=.md

see above for location and plots for fixed spectral index in equatorial

**Comment by NicolettaK** [comment]
@zonca I've compared the power spectra of the new equatorial maps with those of the old galactic ones. In the attached file you can see the spectra for the maps at Nside=512 LAT 27 GHz. There are some differences at small scales, I'm waiting for the maps at Nside=4096 to check the behavior on those.

[spectra_lat.pdf](https://github.com/simonsobs/map_based_simulations/files/3128097/spectra_lat.pdf)

**Comment by zonca** [comment]
@NicolettaK the job timed out, I only got the lowest frequencies at 4096 in the same folder, you can take a look at those.

**Comment by zonca** [comment]
output maps for the 3 simulations at NSIDE 512 are available at NERSC in:

    /global/cscratch1/sd/zonca/simonsobs/mapsims_runs/

**Comment by zonca** [comment]
freefree_pysm3
@NicolettaK I have not identified the cause of that issue in the power spectrum, but I am rerunning this with PySM 3 and that issue is gone.

**Comment by zonca** [comment]
@NicolettaK I have replaced the old nside 512 maps with the new ones, would you check again the folder:

    /global/cscratch1/sd/zonca/simonsobs/mapsims_runs/201904_highres_foregrounds_equatorial/512

the 4096 maps should be ready tomorrow

**Comment by NicolettaK** [comment]
@zonca, I see a sudden drop of the signal amplitude at ell~1000 in the new lat maps at Nside=512. 
[spectra_pysm3.pdf](https://github.com/simonsobs/map_based_simulations/files/3187631/spectra_pysm3.pdf)
I need to check whether this is present also at Nside=4096.

**Comment by zonca** [comment]
ok, nside 4096 are ready:

    /global/cscratch1/sd/zonca/simonsobs/mapsims_runs/201904_highres_foregrounds_equatorial/4096

I am expanding alms up to `nside*2`,  please check those maps, but I'm rerunning again up to `3*nside-1` which is the default for `anafast`

**Comment by NicolettaK** [comment]
ok than this is the reason for the dropping at ell~1000 for Nside=512 maps.

**Comment by zonca** [comment]
ok, new maps with ellmax to 3*nside-1 both 512 and 4096 are ready at:

    /global/cscratch1/sd/zonca/simonsobs/mapsims_runs/201904_highres_foregrounds_equatorial

I moved the others in the subfolder `ellmax_2nside`

**Comment by zonca** [comment]
@NicolettaK ok, variable spectral index maps are ready as well:

    /global/project/projectdirs/sobs/v4_sims/mbs/201904_highres_foregrounds_variable_spectral_index

if you check them I'll wrap up a release of these two and switch to work on extragalactic

**Comment by NicolettaK** [comment]
@Zonca I've checked the maps with spatially constant spectral index and now there is a prefect agreement with the old Galactic maps. I'll try to have a look at the spatially varying in the weekend.

**Comment by zonca** [comment]
ok, this is completed, if you find any problem please open an issue in the repo

**Comment by NicolettaK** [comment]
@zonca, I've just started to check the maps with variable spectral indices. I have realized that having different pivot frequencies for synchrotron temperature and polarization (for T is at 408 MHz, while for P is at 23 GHz) is not ideal, as this causes larger distortion in temperature when you apply a spatially varying scaling. 
Probably it is better to set the pivot frequency at 23 GHz for both T and P. I'll modify the model and do a PR. That means that once this is done we need to run the sims again.

**Comment by zonca** [comment]
ok, no problem, can you please add a note to the README in the meantime https://github.com/simonsobs/map_based_simulations/tree/master/201904_highres_foregrounds_variable_spectral_index and warn people not to use those maps?

**Comment by NicolettaK** [comment]
@zonca could you copy the following files:
`dust_T_ns4096_353GHz.fits`
`dust_T_ns512_353GHz.fits`
`synch_T_ns4096_23GHz.fits`
`synch_T_ns512_23GHz.fits`
from
`/global/cscratch1/sd/krach/SObs/FGawg/so_template`
to the so_pysm_models template directory?

**Comment by zonca** [comment]
copied

**Comment by NicolettaK** [comment]
PR https://github.com/simonsobs/so_pysm_models/pull/38# should solve the problem of pivot frequency for spatially varying spectral indices. @zonca could you run the full sims starting with those at Nside=512?

**Comment by zonca** [comment]
@NicolettaK ok, the are at:

```/global/cscratch1/sd/zonca/simonsobs/mapsims_runs/201904_highres_foregrounds_variable_spectral_index/512```

**Comment by zonca** [comment]
@NicolettaK also 4096 available at the same path

**Pull request merged**
